### ISSUE TITLE
Compiling instructions

### ISSUE THREAD

**Issue by mussingtonr** [norihiro/obs-text-pthread#1]
Hello! Is there instructions on how to compile the project?

**Comment by norihiro** [comment]
Thank you for interesting this plugin.
The build instruction and release of excutables for Windows & MacOS are on my queue.

Dependencies should be same as [obs-text-pango](https://github.com/kkartaltepe/obs-text-pango).
Build step should be similar to [obs-ndi](https://github.com/norihiro/obs-ndi) but not require Qt.

**Comment by mussingtonr** [comment]
Thanks for the replay back! Excited to hear. I'll try to spend some time compiling it tonight with that in mind. If you would like for me to help run tests for the executables for Windows and OSX, I'll stand by. I'm currently running Windows right now but have access to each platform.

**Comment by norihiro** [comment]
Created an article on wiki.
https://github.com/norihiro/obs-text-pthread/wiki/Build
