### ISSUE TITLE
Text Pthread does not render any text

### ISSUE THREAD

**Issue by flexiondotorg** [norihiro/obs-text-pthread#35]
## Expected behaviour

Add Text Pthread source, enter some text and text is rendered.

## Actual behaviour

Add Text Pthread source, enter some text and text not text is rendered.

![image](https://user-images.githubusercontent.com/304639/189649130-c75fb6db-24d5-4c43-9a66-5653e5cfc43c.png)

![image](https://user-images.githubusercontent.com/304639/189649169-20bf8a8a-3a36-4ed8-b717-7e78c631a2fd.png)

I see a line in the OBS log that says:

```
13:01:28.735: [obs-text-pthread] Cannot load '(null)'
13:01:28.803: User added source 'Text Pthread' (obs_text_pthread_source_v2) to scene 'Wimdow Cap'
```

## Configuration

 - Ubuntu 22.04
 - OBS Studio 28.0.1
 - Text Pthread 2.0.1

**Comment by norihiro** [comment]
The error is output when `textalpha.effect` is not loaded correctly. The file structure of the package is changed in OBS 28. I'm I made a mistake when updating the packaging script for this plugin.
https://github.com/norihiro/obs-text-pthread/blob/863ebc7ce8a1b925b716bedf615f62b4d1046818/src/obs-text-pthread-main.c#L52-L55
